---
NXOS-1:
  hostname: 172.20.58.61
  groups:
    - nxos

NXOS-2:
  hostname: 172.20.58.62
  groups:
    - nxos

CSR-1:
  hostname: 172.20.58.51
  groups:
    - iosxe

CSR-2:
  hostname: 172.20.58.52
  groups:
    - iosxe

JT-2960G:
  hostname: 172.20.58.50
  groups:
    - catalyst